# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Introducción a la Econometría Espacial Aplicada
tagline:          ''
description:      'Taller (usando R)' 
url:              "https://uwescience.github.io"
baseurl:          "/t"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/ifarah/t
